import { createApp } from "vue";
import App from "./App.vue";
import BasedCard from "./components/UI/BasedCard.vue";
import BasedButton from "./components/UI/BasedButton.vue";
import BasedDialog from "./components/UI/BasedDialog.vue";
const app = createApp(App);
app.component("BasedCard", BasedCard);
app.component("BasedButton", BasedButton);
app.component("BasedDialog", BasedDialog);
app.mount("#app");
